// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJF451eU46XMirmtBaLH9kgM5jrlLH7SU',
    appId: '1:296607228397:web:24495a3e2db0f4127d87e4',
    messagingSenderId: '296607228397',
    projectId: 'ischool-web-a2d36',
    authDomain: 'ischool-web-a2d36.firebaseapp.com',
    databaseURL: 'https://ischool-web-a2d36-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ischool-web-a2d36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNnXNKLpb0ekwwfMiMRUh7URu6im-t8_o',
    appId: '1:296607228397:android:c361367d009dbe717d87e4',
    messagingSenderId: '296607228397',
    projectId: 'ischool-web-a2d36',
    databaseURL: 'https://ischool-web-a2d36-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ischool-web-a2d36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAfveF8ATueHy8u1XnV5nAJnKNlQtBDvA',
    appId: '1:296607228397:ios:59f622dc7f7b71407d87e4',
    messagingSenderId: '296607228397',
    projectId: 'ischool-web-a2d36',
    databaseURL: 'https://ischool-web-a2d36-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ischool-web-a2d36.appspot.com',
    iosBundleId: 'com.example.trackerLoginRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAfveF8ATueHy8u1XnV5nAJnKNlQtBDvA',
    appId: '1:296607228397:ios:59f622dc7f7b71407d87e4',
    messagingSenderId: '296607228397',
    projectId: 'ischool-web-a2d36',
    databaseURL: 'https://ischool-web-a2d36-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ischool-web-a2d36.appspot.com',
    iosBundleId: 'com.example.trackerLoginRegister',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJF451eU46XMirmtBaLH9kgM5jrlLH7SU',
    appId: '1:296607228397:web:af407c930add15547d87e4',
    messagingSenderId: '296607228397',
    projectId: 'ischool-web-a2d36',
    authDomain: 'ischool-web-a2d36.firebaseapp.com',
    databaseURL: 'https://ischool-web-a2d36-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ischool-web-a2d36.appspot.com',
  );

}